class_names:
  - object
  - pipe_fryum
  - metal_nut
  - pcb1
  - tile
  - screw
  - pcb2
  - wood
  - zipper
  - cable
  - fryum
  - pill
  - capsule
  - hazelnut
  - pcb4
  - leather
  - bottle
  - cashew
  - macaroni2
  - grid
  - chewinggum
  - transistor
  - macaroni1
  - candle
  - capsules
  - pcb3
  - carpet
  - toothbrush
