state_template:
  anomaly:
  - a photo of the damaged {}.
  - a bright photo of the damaged {}.
  - a dark photo of the damaged {}.
  - a close-up photo of the damaged {}.
  - a black and white photo of the damaged {}.
  - a blurry photo of the damaged {}.
  - a blurry photo of a damaged {}.
  - a photo of the small damaged {}.
  - a photo of the large damaged {}.
  - there is a damaged {} in the scene.
  - this is one damaged {} in the scene.
  - a photo of the broken {}.
  - a bright photo of the broken {}.
  - a dark photo of the broken {}.
  - a close-up photo of the broken {}.
  - a black and white photo of the broken {}.
  - a blurry photo of the broken {}.
  - a blurry photo of a broken {}.
  - a photo of the small broken {}.
  - a photo of the large broken {}.
  - there is a broken {} in the scene.
  - this is one broken {} in the scene.
  - a photo of the {} with flaw.
  - a bright photo of the {} with flaw.
  - a dark photo of the {} with flaw.
  - a close-up photo of the {} with flaw.
  - a black and white photo of the {} with flaw.
  - a blurry photo of the {} with flaw.
  - a blurry photo of a {} with flaw.
  - a photo of the small {} with flaw.
  - a photo of the large {} with flaw.
  - there is a {} with flaw in the scene.
  - this is one {} with flaw in the scene.
  - a photo of the {} with defect.
  - a bright photo of the {} with defect.
  - a dark photo of the {} with defect.
  - a close-up photo of the {} with defect.
  - a black and white photo of the {} with defect.
  - a blurry photo of the {} with defect.
  - a blurry photo of a {} with defect.
  - a photo of the small {} with defect.
  - a photo of the large {} with defect.
  - there is a {} with defect in the scene.
  - this is one {} with defect in the scene.
  normal:
  - a photo of the {}.
  - a bright photo of the {}.
  - a dark photo of the {}.
  - a close-up photo of the {}.
  - a black and white photo of the {}.
  - a blurry photo of the {}.
  - a blurry photo of a {}.
  - a photo of the small {}.
  - a photo of the large {}.
  - there is a {} in the scene.
  - this is one {} in the scene.
  - a photo of the flawless {}.
  - a bright photo of the flawless {}.
  - a dark photo of the flawless {}.
  - a close-up photo of the flawless {}.
  - a black and white photo of the flawless {}.
  - a blurry photo of the flawless {}.
  - a blurry photo of a flawless {}.
  - a photo of the small flawless {}.
  - a photo of the large flawless {}.
  - there is a flawless {} in the scene.
  - this is one flawless {} in the scene.
  - a photo of the {} without flaw.
  - a bright photo of the {} without flaw.
  - a dark photo of the {} without flaw.
  - a close-up photo of the {} without flaw.
  - a black and white photo of the {} without flaw.
  - a blurry photo of the {} without flaw.
  - a blurry photo of a {} without flaw.
  - a photo of the small {} without flaw.
  - a photo of the large {} without flaw.
  - there is a {} without flaw in the scene.
  - this is one {} without flaw in the scene.
  - a photo of the {} without defect.
  - a bright photo of the {} without defect.
  - a dark photo of the {} without defect.
  - a close-up photo of the {} without defect.
  - a black and white photo of the {} without defect.
  - a blurry photo of the {} without defect.
  - a blurry photo of a {} without defect.
  - a photo of the small {} without defect.
  - a photo of the large {} without defect.
  - there is a {} without defect in the scene.
  - this is one {} without defect in the scene.
