# @package _global_

defaults:
  - _self_
  - data: anomaly_clip # choose datamodule with `test_dataloader()` for evaluation
  - model: anomaly_clip
  - callbacks: default
  - logger: many_loggers
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # information of object and prompt template
  - prompt: default

task_name: "eval"

tags: ["dev"]

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# passing checkpoint path is necessary for evaluation
# ckpt_path: /home/hzx/Projects/SPARC/logs/train/runs/2024-06-14_16-32-14/checkpoints/epoch_000.ckpt
# ckpt_path: /home/hzx/Projects/Weight/mvtech-kshot/learnable/0-shot/2024-05-27_13-08-55/checkpoints/epoch_000.ckpt
ckpt_path: /home/hzx/Projects/Weight/visa-kshot/learnable/0-shot/2024-05-27_11-07-16/checkpoints/epoch_000.ckpt
